apiVersion: v1
appVersion: "1.0"
description: A Kubernetes Helm chart for Automation Frame Work Core-SVN Component Registry
name: coresvn-registry
name-registryui: coresvn-registryui
version: 0.1.0
maintainers:
  - name: F0otsh0T
    email: jychen1@hotmail.com
