apiVersion: v1
kind: Service
metadata:
  name: {{ template "registry.fullname" . }}
  labels:
    app: {{ template "registry.name" . }}
    chart: {{ template "registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.Service.type }}
  ports:
    - port: {{ .Values.Service.port }}
      targetPort: {{ .Values.Service.targetport }}
      nodePort: {{ .Values.Service.nodeport }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "registry.name" . }}
    release: {{ .Release.Name }}
